In [2]:
import pybaseball as pyb
import pandas as pd
import numpy as np
import os
import datetime

Matplotlib is building the font cache; this may take a moment.

In [15]:
pyb.playerid_lookup('Guerrero', 'vladimir', fuzzy=True)

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,guerrero,vladimir,665489,guerv002,guerrvl02,19611,2019.0,2025.0
1,guerrero,vladimir,115223,guerv001,guerrvl01,778,1996.0,2011.0

In [16]:
# 
pyb.statcast_batter_exitvelo_barrels(2025)

,"last_name, first_name",player_id,attempts,avg_hit_angle,anglesweetspotpercent,max_hit_speed,avg_hit_speed,ev50,fbld,gb,max_distance,avg_distance,avg_hr_distance,ev95plus,ev95percent,barrels,brl_percent,brl_pa
0,"Bichette, Bo",666182,89,11.0,43.8,110.6,90.5,101.5,96.2,87.4,372,164,NaN,43,48.3,7,7.9,6.3
1,"Arraez, Luis",650333,88,11.3,40.9,107.8,87.6,94.4,89.3,85.1,376,158,355.0,21,23.9,0,0.0,0.0
2,"Happ, Ian",664023,88,17.9,38.6,112.0,88.0,100.1,93.2,83.7,404,173,374.0,33,37.5,8,9.1,6.5
3,"Tucker, Kyle",663656,87,20.2,42.5,108.1,90.8,100.4,94.1,84.8,427,210,402.0,38,43.7,14,16.1,11.8
4,"DÃ­az, Yandy",650490,82,0.8,23.2,112.5,90.9,103.7,97.1,88.9,415,130,378.0,39,47.6,7,8.5,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,"De La Cruz, Bryan",650559,29,15.6,44.8,106.5,91.5,101.4,94.7,87.9,368,179,NaN,15,51.7,2,6.9,4.0
264,"Rodgers, Brendan",663898,28,15.0,42.9,112.2,90.4,102.8,90.4,95.0,363,188,NaN,14,50.0,4,14.3,7.5
265,"Marsh, Brandon",669016,28,7.5,21.4,105.0,90.3,99.2,95.3,84.8,395,156,395.0,13,46.4,2,7.1,3.9
266,"Melendez, MJ",669004,27,23.6,29.6,108.5,90.1,99.3,95.7,83.9,429,187,429.0,12,44.4,3,11.1,5.8
267,"Murphy, Sean",669221,26,9.0,38.5,112.5,91.4,103.0,96.7,84.3,429,188,400.0,11,42.3,6,23.1,12.0

In [ ]:
df = pyb.statcast_batter('2025-03-25', )

Gathering Player Data

In [22]:
df_batting_2025 = pyb.batting_stats(2025)

In [ ]:
df_batting_2025

In [35]:
df

Empty DataFrame
Columns: [pitch_type, game_date, release_speed, release_pos_x, release_pos_z, player_name, batter, pitcher, events, description, spin_dir, spin_rate_deprecated, break_angle_deprecated, break_length_deprecated, zone, des, game_type, stand, p_throws, home_team, away_team, type, hit_location, bb_type, balls, strikes, game_year, pfx_x, pfx_z, plate_x, plate_z, on_3b, on_2b, on_1b, outs_when_up, inning, inning_topbot, hc_x, hc_y, tfs_deprecated, tfs_zulu_deprecated, umpire, sv_id, vx0, vy0, vz0, ax, ay, az, sz_top, sz_bot, hit_distance_sc, launch_speed, launch_angle, effective_speed, release_spin_rate, release_extension, game_pk, fielder_2, fielder_3, fielder_4, fielder_5, fielder_6, fielder_7, fielder_8, fielder_9, release_pos_y, estimated_ba_using_speedangle, estimated_woba_using_speedangle, woba_value, woba_denom, babip_value, iso_value, launch_speed_angle, at_bat_number, pitch_number, pitch_name, home_score, away_score, bat_score, fld_score, post_away_score, post_home_score, post_bat_score, post_fld_score, if_fielding_alignment, of_fielding_alignment, spin_axis, delta_home_win_exp, delta_run_exp, bat_speed, swing_length, estimated_slg_using_speedangle, delta_pitcher_run_exp, hyper_speed, home_score_diff, bat_score_diff, home_win_exp, bat_win_exp, age_pit_legacy, ...]
Index: []

[0 rows x 113 columns]

## AL East

### Blue Jays: Vlad for average and power
Tony Fernandez has the most seasons with at least a .310 BA. Vlad Jr has done it twice so far. Will 2025 be Year 3?
Also, since 2021 Vlad Jr has the second most batted balls with above 115 mph exit velo. Stanton has the most at 95.

In [ ]:
# Create a function that takes df_batting_2025 and returns a True/False value if Vlad's batting average is currently above .310 and also returns the current batting average.
def is_vlad_batting_above_310(df, id_fg):
    # Get Vlad's batting average
    vlad_batting_avg = df.loc[df['IDfg'] == id_fg, 'AVG'].values[0]
    
    # Check if batting average is above .310
    if vlad_batting_avg > .310:
        return True, vlad_batting_avg
    else:
        return False, vlad_batting_avg
    
# TODO: Research what counts as a batted ball to also track number of batted balls over 115 mph by Vlad Jr.

In [36]:
is_vlad_batting_above_310(df_batting_2025, 19611)

(False, np.float64(0.278))

### Orioles: Ground Chuck
 -- Nothing to Track

### Rays: Yandyâs unique ability